version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000" # host:image
    volumes:
      - ./app:/app # real-time updates between project and container
    command: > # all container ip (0.0.0.0)
      sh -c "python manage.py runserver 0.0.0.0:8000"
